import ExcelJS from 'exceljs';
import path from 'path';
import fs from 'fs';

type TestType = 'Positive' | 'Negative';
type Status = 'PASS' | 'FAIL' | 'N/A';

interface MasterTC {
  tcId: string;
  module: string;
  subModule: string;
  testType: TestType;
  description: string;
  preconditions: string;
  testData: string;
  testSteps: string;
  expectedResult: string;
  status: Status;
}

const testCases: MasterTC[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // LOGIN
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_LOGIN_001', module:'Login', subModule:'Login', testType:'Positive', description:'AdminMaker login with valid credentials', preconditions:'AdminMaker account is active.', testData:'Username: AdminMaker\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter valid username\n3. Enter valid password\n4. Click Sign In\n5. Assert URL not /login', expectedResult:'User redirected away from /login.', status:'PASS' },
  { tcId:'TC_LOGIN_002', module:'Login', subModule:'Login', testType:'Negative', description:'AdminMaker login with invalid password', preconditions:'AdminMaker account is active.', testData:'Username: AdminMaker\nPassword: WrongPassword@999', testSteps:'1. Navigate to /login\n2. Enter valid username\n3. Enter invalid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails. User stays on /login.', status:'PASS' },
  { tcId:'TC_LOGIN_003', module:'Login', subModule:'Login', testType:'Negative', description:'AdminMaker login with invalid username', preconditions:'', testData:'Username: InvalidUser_999\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter invalid username\n3. Enter valid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails. User stays on /login.', status:'PASS' },
  { tcId:'TC_LOGIN_004', module:'Login', subModule:'Login', testType:'Negative', description:'Login button disabled when credentials empty', preconditions:'', testData:'Username: (empty)\nPassword: (empty)', testSteps:'1. Navigate to /login\n2. Leave fields empty\n3. Assert Login button disabled', expectedResult:'Login button is disabled.', status:'PASS' },
  { tcId:'TC_LOGIN_005', module:'Login', subModule:'Login', testType:'Positive', description:'AdminChecker login with valid credentials', preconditions:'AdminChecker account is active.', testData:'Username: AdminChecker\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter valid credentials\n3. Click Sign In\n4. Assert URL not /login', expectedResult:'User redirected away from /login.', status:'PASS' },
  { tcId:'TC_LOGIN_006', module:'Login', subModule:'Login', testType:'Negative', description:'AdminChecker login with invalid password', preconditions:'', testData:'Username: AdminChecker\nPassword: Invalid@Pass', testSteps:'1. Navigate to /login\n2. Enter valid username\n3. Enter invalid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails.', status:'PASS' },
  { tcId:'TC_LOGIN_007', module:'Login', subModule:'Login', testType:'Negative', description:'AdminChecker login with invalid username', preconditions:'', testData:'Username: InvalidChecker_999\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter invalid username\n3. Enter valid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails.', status:'PASS' },
  { tcId:'TC_LOGIN_008', module:'Login', subModule:'Login', testType:'Positive', description:'Labesh_Maker login with valid credentials', preconditions:'Labesh_Maker account is active.', testData:'Username: Labesh_Maker\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter valid credentials\n3. Click Sign In\n4. Assert URL not /login', expectedResult:'User redirected away from /login.', status:'PASS' },
  { tcId:'TC_LOGIN_009', module:'Login', subModule:'Login', testType:'Negative', description:'Labesh_Maker login with invalid password', preconditions:'', testData:'Username: Labesh_Maker\nPassword: Wrong@Pass', testSteps:'1. Navigate to /login\n2. Enter valid username\n3. Enter invalid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails.', status:'PASS' },
  { tcId:'TC_LOGIN_010', module:'Login', subModule:'Login', testType:'Negative', description:'Labesh_Maker login with invalid username', preconditions:'', testData:'Username: InvalidLabesh_999\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter invalid username\n3. Enter valid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails.', status:'PASS' },
  { tcId:'TC_LOGIN_011', module:'Login', subModule:'Login', testType:'Positive', description:'LabeshChecker login with valid credentials', preconditions:'LabeshChecker account is active.', testData:'Username: LabeshChecker\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter valid credentials\n3. Click Sign In\n4. Assert URL not /login', expectedResult:'User redirected away from /login.', status:'PASS' },
  { tcId:'TC_LOGIN_012', module:'Login', subModule:'Login', testType:'Negative', description:'LabeshChecker login with invalid password', preconditions:'', testData:'Username: LabeshChecker\nPassword: Wrong@Pass', testSteps:'1. Navigate to /login\n2. Enter valid username\n3. Enter invalid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails.', status:'PASS' },
  { tcId:'TC_LOGIN_013', module:'Login', subModule:'Login', testType:'Negative', description:'LabeshChecker login with invalid username', preconditions:'', testData:'Username: InvalidLabeshChecker_999\nPassword: Pakistan@1234', testSteps:'1. Navigate to /login\n2. Enter invalid username\n3. Enter valid password\n4. Click Sign In\n5. Assert URL still /login', expectedResult:'Login fails.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // AGGREGATOR CREATION
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_AGG_E2E_001', module:'Aggregator Management', subModule:'Create & Approve', testType:'Positive', description:'Full E2E aggregator creation and approval', preconditions:'AdminMaker and AdminChecker accounts active.', testData:'Name: Auto_Aggregator_<ts>, Email: aggregator<ts>@yopmail.com, Phone: 7<8digits>, QR: checked, Comment: Approved by AdminChecker', testSteps:'1. Login as AdminMaker\n2. Go to Aggregator List\n3. Click Add Aggregator\n4. Fill all fields with unique data\n5. Select QR\n6. Save and verify Processed OK\n7. Logout\n8. Login as AdminChecker\n9. Go to Inbox > Pending Processes\n10. Review AGGREGATOR CREATION\n11. Approve with comment\n12. Verify Process approved successfully', expectedResult:'Processed OK on creation. Process approved successfully on approval.', status:'PASS' },
  { tcId:'TC_AGG_NEG_001', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'All fields empty shows required errors', preconditions:'Add Aggregator form is open.', testData:'All fields: (empty)', testSteps:'1. Open Add Aggregator form\n2. Leave all fields empty\n3. Click Save\n4. Assert all 5 required errors visible', expectedResult:'All 5 required field errors shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_002', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Missing Aggregator Name shows error', preconditions:'', testData:'Name: (empty), rest valid', testSteps:'1. Open form\n2. Leave Name empty\n3. Fill others\n4. Click Save\n5. Assert "Aggregator name is required"', expectedResult:'"Aggregator name is required" shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_003', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Numeric-only name shows validation error', preconditions:'', testData:'Name: 123456789', testSteps:'1. Open form\n2. Enter "123456789" in Name\n3. Fill others\n4. Click Save\n5. Assert validation error', expectedResult:'Validation error for numeric-only name.', status:'PASS' },
  { tcId:'TC_AGG_NEG_004', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Missing Contact Person shows error', preconditions:'', testData:'Contact: (empty), rest valid', testSteps:'1. Open form\n2. Leave Contact Person empty\n3. Fill others\n4. Click Save\n5. Assert "Contact person name is required"', expectedResult:'"Contact person name is required" shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_005', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Missing Email shows error', preconditions:'', testData:'Email: (empty), rest valid', testSteps:'1. Open form\n2. Leave Email empty\n3. Fill others\n4. Click Save\n5. Assert "Invalid email format"', expectedResult:'"Invalid email format" shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_006', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Invalid email (missing @)', preconditions:'', testData:'Email: invalidemail.com', testSteps:'1. Open form\n2. Enter "invalidemail.com"\n3. Fill others\n4. Click Save\n5. Assert "Invalid email format"', expectedResult:'"Invalid email format" shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_007', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Invalid email (double @@)', preconditions:'', testData:'Email: test@@yopmail.com', testSteps:'1. Open form\n2. Enter "test@@yopmail.com"\n3. Fill others\n4. Click Save\n5. Assert "Invalid email format"', expectedResult:'"Invalid email format" shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_008', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Missing Phone shows error', preconditions:'', testData:'Phone: (empty), rest valid', testSteps:'1. Open form\n2. Leave Phone empty\n3. Fill others\n4. Click Save\n5. Assert "Phone number is required"', expectedResult:'"Phone number is required" shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_009', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'Non-numeric phone stays empty', preconditions:'', testData:'Phone: ABCDEFGH', testSteps:'1. Open form\n2. Type "ABCDEFGH" in Phone\n3. Assert field is empty\n4. Click Save\n5. Assert "Phone number is required"', expectedResult:'Field rejects alphabets. Error shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_010', module:'Aggregator Management', subModule:'Create - Validation', testType:'Negative', description:'No payment method selected', preconditions:'', testData:'QR: not checked', testSteps:'1. Open form\n2. Fill all fields\n3. Do NOT check QR\n4. Click Save\n5. Assert "At least one payment method must be selected"', expectedResult:'"At least one payment method" error shown.', status:'PASS' },
  { tcId:'TC_AGG_NEG_011', module:'Aggregator Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker cannot Approve without comment', preconditions:'Pending AGGREGATOR CREATION exists.', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review AGGREGATOR CREATION\n3. Click Approve\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm button disabled.', status:'PASS' },
  { tcId:'TC_AGG_NEG_012', module:'Aggregator Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker cannot Reject without comment', preconditions:'', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review AGGREGATOR CREATION\n3. Click Reject\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm button disabled.', status:'PASS' },
  { tcId:'TC_AGG_NEG_013', module:'Aggregator Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker rejects aggregator creation with valid reason', preconditions:'', testData:'Comment: Rejected by AdminChecker', testSteps:'1. Login as Checker\n2. Review AGGREGATOR CREATION\n3. Click Reject\n4. Enter comment\n5. Confirm\n6. Assert "Process rejected"', expectedResult:'"Process rejected" toast shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // AGGREGATOR UPDATE
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_AGG_UPD_E2E_001', module:'Aggregator Management', subModule:'Update & Approve', testType:'Positive', description:'Full E2E aggregator update and approval', preconditions:'An aggregator exists.', testData:'Updated Name: Auto_Aggregator_Update_<ts>, Updated Email: aggregatorupdate<ts>@yopmail.com, Comment: Approved by AdminChecker', testSteps:'1. Login as AdminMaker\n2. Click Edit on first aggregator\n3. Update Name and Email\n4. Save and verify Processed OK\n5. Logout\n6. Login as AdminChecker\n7. Review AGGREGATOR UPDATE\n8. Approve with comment\n9. Verify Process approved successfully', expectedResult:'Update approved successfully.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_001', module:'Aggregator Management', subModule:'Update - Validation', testType:'Negative', description:'Clear Name shows error', preconditions:'Edit form open.', testData:'Name: (cleared)', testSteps:'1. Open Edit form\n2. Clear Name\n3. Click Save\n4. Assert "Aggregator name is required"', expectedResult:'Error shown.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_002', module:'Aggregator Management', subModule:'Update - Validation', testType:'Negative', description:'Clear Contact Person shows error', preconditions:'', testData:'Contact: (cleared)', testSteps:'1. Open Edit form\n2. Clear Contact Person\n3. Click Save\n4. Assert "Contact person name is required"', expectedResult:'Error shown.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_003', module:'Aggregator Management', subModule:'Update - Validation', testType:'Negative', description:'Clear Email shows error', preconditions:'', testData:'Email: (cleared)', testSteps:'1. Open Edit form\n2. Clear Email\n3. Click Save\n4. Assert "Invalid email format"', expectedResult:'Error shown.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_004', module:'Aggregator Management', subModule:'Update - Validation', testType:'Negative', description:'Invalid email format (missing @)', preconditions:'', testData:'Email: invalidemail.com', testSteps:'1. Open Edit form\n2. Enter invalidemail.com\n3. Click Save\n4. Assert "Invalid email format"', expectedResult:'Error shown.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_005', module:'Aggregator Management', subModule:'Update - Validation', testType:'Negative', description:'Clear Phone shows error', preconditions:'', testData:'Phone: (cleared)', testSteps:'1. Open Edit form\n2. Clear Phone\n3. Click Save\n4. Assert "Phone number is required"', expectedResult:'Error shown.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_006', module:'Aggregator Management', subModule:'Update - Validation', testType:'Negative', description:'Non-numeric phone stays empty', preconditions:'', testData:'Phone: ABCDEFGH', testSteps:'1. Open Edit form\n2. Type "ABCDEFGH" in Phone\n3. Assert field empty\n4. Click Save\n5. Assert "Phone number is required"', expectedResult:'Error shown.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_007', module:'Aggregator Management', subModule:'Update - Validation', testType:'Negative', description:'Uncheck QR shows error', preconditions:'', testData:'QR: unchecked', testSteps:'1. Open Edit form\n2. Uncheck QR\n3. Click Save\n4. Assert "At least one payment method must be selected"', expectedResult:'Error shown.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_008', module:'Aggregator Management', subModule:'Update - Approval Validation', testType:'Negative', description:'Checker cannot Approve update without comment', preconditions:'Pending AGGREGATOR UPDATE exists.', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review AGGREGATOR UPDATE\n3. Click Approve\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm button disabled.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_009', module:'Aggregator Management', subModule:'Update - Approval Validation', testType:'Negative', description:'Checker cannot Reject update without comment', preconditions:'', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review AGGREGATOR UPDATE\n3. Click Reject\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm button disabled.', status:'PASS' },
  { tcId:'TC_AGG_UPD_NEG_010', module:'Aggregator Management', subModule:'Update - Approval Validation', testType:'Negative', description:'Checker rejects aggregator update', preconditions:'', testData:'Comment: Rejected - Invalid details', testSteps:'1. Login as Checker\n2. Review AGGREGATOR UPDATE\n3. Click Reject\n4. Enter comment\n5. Confirm\n6. Assert "Process rejected"', expectedResult:'"Process rejected" toast shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // ROLE CREATION
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_ROLE_E2E_001', module:'User & Role Management', subModule:'Role Create & Approve', testType:'Positive', description:'Full E2E role creation and approval', preconditions:'AdminMaker and AdminChecker active.', testData:'Role Name: AutoRole_<ts>, Description: AutoDesc_<ts>, All permissions selected, Comment: Approved by AdminChecker', testSteps:'1. Login as AdminMaker\n2. Go to Role List\n3. Click Add Role\n4. Fill unique Role Name and Description\n5. Select all permissions\n6. Click Save\n7. Verify Processed OK\n8. Logout\n9. Login as AdminChecker\n10. Go to Inbox > Pending Processes\n11. Review ROLE CREATION\n12. Approve with comment\n13. Verify Process approved successfully', expectedResult:'Role created and approved successfully.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_001', module:'User & Role Management', subModule:'Role - Validation', testType:'Negative', description:'All fields empty shows validation errors', preconditions:'Add Role form open.', testData:'All fields: (empty)', testSteps:'1. Open Add Role form\n2. Leave all fields empty\n3. Click Save\n4. Assert "Name must be at least 4 characters"\n5. Assert "Description must be at least 4 characters"\n6. Assert "Please select at least one permission"', expectedResult:'All validation errors shown.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_002', module:'User & Role Management', subModule:'Role - Validation', testType:'Negative', description:'Role Name less than 4 chars shows error', preconditions:'', testData:'Role Name: AB', testSteps:'1. Open Add Role form\n2. Enter "AB" as Role Name\n3. Click Save\n4. Assert "Name must be at least 4 characters"', expectedResult:'Validation error shown.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_003', module:'User & Role Management', subModule:'Role - Validation', testType:'Negative', description:'Description less than 4 chars shows error', preconditions:'', testData:'Description: XY', testSteps:'1. Open Add Role form\n2. Enter "XY" in Description\n3. Click Save\n4. Assert "Description must be at least 4 characters"', expectedResult:'Validation error shown.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_004', module:'User & Role Management', subModule:'Role - Validation', testType:'Negative', description:'No permission selected shows error', preconditions:'', testData:'Permissions: none', testSteps:'1. Open Add Role form\n2. Fill Name and Description\n3. Do not select any permission\n4. Click Save\n5. Assert "Please select at least one permission"', expectedResult:'Validation error shown.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_005', module:'User & Role Management', subModule:'Role - Approval Validation', testType:'Negative', description:'Checker cannot Approve without comment', preconditions:'Pending ROLE CREATION exists.', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review ROLE CREATION\n3. Click Approve\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm button disabled.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_006', module:'User & Role Management', subModule:'Role - Approval Validation', testType:'Negative', description:'Checker cannot Reject without comment', preconditions:'', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review ROLE CREATION\n3. Click Reject\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm button disabled.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_007', module:'User & Role Management', subModule:'Role - Approval Validation', testType:'Negative', description:'Checker rejects role creation', preconditions:'', testData:'Comment: Rejected', testSteps:'1. Login as Checker\n2. Review ROLE CREATION\n3. Click Reject\n4. Enter comment\n5. Confirm\n6. Assert "Process rejected"', expectedResult:'"Process rejected" toast shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // TILL MANAGEMENT
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_TILL_001', module:'Till Management', subModule:'Add Till', testType:'Positive', description:'Add terminal and checker approves', preconditions:'Maker and Checker active. Merchant exists.', testData:'Terminal name, email, mobile, location, merchant (all unique)', testSteps:'1. Login as Maker\n2. Go to Till Management\n3. Click Add Terminal\n4. Fill all fields\n5. Select merchant\n6. Save and verify Processed OK\n7. Logout\n8. Login as Checker\n9. Review TERMINAL CREATION\n10. Approve with comment', expectedResult:'Terminal created and approved.', status:'PASS' },
  { tcId:'TC_TILL_002', module:'Till Management', subModule:'Add Till', testType:'Positive', description:'Add second terminal with different data', preconditions:'', testData:'Different unique values for all fields', testSteps:'Same as TC_TILL_001 with different data', expectedResult:'Terminal created and approved.', status:'PASS' },
  { tcId:'TC_TILL_003', module:'Till Management', subModule:'Add Till', testType:'Positive', description:'Add third terminal with different data', preconditions:'', testData:'Different unique values for all fields', testSteps:'Same as TC_TILL_001 with different data', expectedResult:'Terminal created and approved.', status:'PASS' },
  { tcId:'TC_TILL_004', module:'Till Management', subModule:'Update Till', testType:'Positive', description:'Edit terminal name and status, checker approves', preconditions:'Terminal exists.', testData:'New name, new status', testSteps:'1. Login as Maker\n2. Click Edit on first terminal\n3. Update name and status\n4. Save and verify Processed OK\n5. Logout\n6. Login as Checker\n7. Review TERMINAL UPDATE\n8. Approve', expectedResult:'Update approved successfully.', status:'PASS' },
  { tcId:'TC_TILL_005', module:'Till Management', subModule:'Update Till', testType:'Positive', description:'Edit terminal with different values, approve', preconditions:'', testData:'Different update values', testSteps:'Same as TC_TILL_004', expectedResult:'Update approved.', status:'PASS' },
  { tcId:'TC_TILL_006', module:'Till Management', subModule:'Reject Flow', testType:'Positive', description:'Checker rejects terminal creation, maker acknowledges', preconditions:'', testData:'Checker reject comment', testSteps:'1. Maker creates terminal\n2. Checker rejects\n3. Maker rejects in Maker Pending', expectedResult:'Process rejected by both.', status:'PASS' },
  { tcId:'TC_TILL_007', module:'Till Management', subModule:'Reject Flow', testType:'Positive', description:'Checker rejects terminal update', preconditions:'', testData:'Checker reject comment', testSteps:'1. Maker updates terminal\n2. Checker rejects\n3. Maker acknowledges', expectedResult:'Update rejected by checker.', status:'PASS' },
  { tcId:'TC_TILL_008', module:'Till Management', subModule:'View', testType:'Positive', description:'View terminal details', preconditions:'Terminal exists.', testData:'N/A', testSteps:'1. Login as Maker\n2. Click View on first terminal\n3. Assert View Terminal heading\n4. Click Go Back', expectedResult:'View page opens and Go Back returns to list.', status:'PASS' },
  { tcId:'TC_TILL_009', module:'Till Management', subModule:'Filter - Profile Name', testType:'Positive', description:'Filter by profile name returns matching results', preconditions:'Terminals exist.', testData:'Profile name search term', testSteps:'1. Open Filter\n2. Enter profile name\n3. Apply\n4. Assert results\n5. Reset', expectedResult:'Matching terminals shown.', status:'FAIL' },
  { tcId:'TC_TILL_010', module:'Till Management', subModule:'Filter - Status', testType:'Positive', description:'Filter by status returns matching results', preconditions:'', testData:'Status: Active', testSteps:'1. Open Filter\n2. Select Status: Active\n3. Apply\n4. Assert ACTIVE cell\n5. Reset', expectedResult:'Active terminals shown.', status:'FAIL' },
  { tcId:'TC_TILL_011', module:'Till Management', subModule:'Filter - Date', testType:'Positive', description:'Quick select date filter works', preconditions:'', testData:'Quick select: Today', testSteps:'1. Open Filter\n2. Click Today\n3. Assert table or no data\n4. Reset', expectedResult:'Filter applied correctly.', status:'PASS' },
  { tcId:'TC_TILL_012', module:'Till Management', subModule:'Filter - Reset', testType:'Positive', description:'Reset clears all filter values', preconditions:'', testData:'Profile name filter applied first', testSteps:'1. Open Filter\n2. Apply name filter\n3. Reset\n4. Assert input empty', expectedResult:'All filters cleared.', status:'PASS' },
  { tcId:'TC_TILL_NEG_001', module:'Till Management', subModule:'Add - Validation', testType:'Negative', description:'All fields empty shows validation errors', preconditions:'Add Terminal form open.', testData:'All fields: (empty)', testSteps:'1. Open Add Terminal form\n2. Leave all empty\n3. Click Save\n4. Assert required errors', expectedResult:'Validation errors shown.', status:'PASS' },
  { tcId:'TC_TILL_NEG_002', module:'Till Management', subModule:'Add - Validation', testType:'Negative', description:'Missing terminal name shows error', preconditions:'', testData:'Name: (empty)', testSteps:'1. Open form\n2. Leave Name empty\n3. Fill others\n4. Click Save\n5. Assert name required error', expectedResult:'Name required error shown.', status:'PASS' },
  { tcId:'TC_TILL_NEG_003', module:'Till Management', subModule:'Add - Validation', testType:'Negative', description:'Invalid email format shows error', preconditions:'', testData:'Email: invalidemail', testSteps:'1. Open form\n2. Enter invalid email\n3. Click Save\n4. Assert email format error', expectedResult:'Email format error shown.', status:'PASS' },
  { tcId:'TC_TILL_NEG_004', module:'Till Management', subModule:'Add - Validation', testType:'Negative', description:'Missing mobile shows error', preconditions:'', testData:'Mobile: (empty)', testSteps:'1. Open form\n2. Leave mobile empty\n3. Fill others\n4. Click Save\n5. Assert mobile required error', expectedResult:'Mobile required error.', status:'PASS' },
  { tcId:'TC_TILL_NEG_005', module:'Till Management', subModule:'Add - Validation', testType:'Negative', description:'No merchant selected shows error', preconditions:'', testData:'Merchant: (none)', testSteps:'1. Open form\n2. Fill all except merchant\n3. Click Save\n4. Assert merchant required error', expectedResult:'Merchant required error.', status:'PASS' },
  { tcId:'TC_TILL_NEG_006', module:'Till Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker cannot Approve without comment', preconditions:'Pending TERMINAL CREATION.', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review TERMINAL CREATION\n3. Click Approve\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm disabled.', status:'PASS' },
  { tcId:'TC_TILL_NEG_007', module:'Till Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker cannot Reject without comment', preconditions:'', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review TERMINAL CREATION\n3. Click Reject\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm disabled.', status:'PASS' },
  { tcId:'TC_TILL_NEG_008', module:'Till Management', subModule:'Filter - Negative', testType:'Negative', description:'Non-existent name shows No data found', preconditions:'', testData:'Name: zzz_nonexistent_999', testSteps:'1. Open Filter\n2. Enter zzz_nonexistent_999\n3. Apply\n4. Assert No data found\n5. Reset', expectedResult:'"No data found" shown.', status:'PASS' },
  { tcId:'TC_TILL_NEG_009', module:'Till Management', subModule:'Filter - Negative', testType:'Negative', description:'Invalid date range shows validation error', preconditions:'', testData:'From: 31/05/2026, To: 08/05/2026', testSteps:'1. Open Filter\n2. Set From > To date\n3. Apply\n4. Assert date error\n5. Reset', expectedResult:'Date validation error shown.', status:'PASS' },
  { tcId:'TC_TILL_NEG_010', module:'Till Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker rejects terminal creation', preconditions:'', testData:'Comment: Rejected', testSteps:'1. Login as Checker\n2. Review TERMINAL CREATION\n3. Click Reject\n4. Enter comment\n5. Confirm\n6. Assert "Process rejected"', expectedResult:'"Process rejected" shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // NOTIFICATION TEMPLATE
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_NOTIF_001', module:'Notification Management', subModule:'Create & Approve', testType:'Positive', description:'Maker creates notification template and Checker approves', preconditions:'Maker and Checker accounts active.', testData:'Template Name: AutoTest_Template_<ts>, Event Type: LOGIN_ALERT, Channel: EMAIL, Subject, Body', testSteps:'1. Login as Maker\n2. Go to Notifications List\n3. Click Add Notifications\n4. Fill all fields\n5. Save and verify Processed OK\n6. Logout\n7. Login as Checker\n8. Review NOTIFICATION CREATION\n9. Approve with comment', expectedResult:'Template created and approved.', status:'PASS' },
  { tcId:'TC_NOTIF_002', module:'Notification Management', subModule:'View', testType:'Positive', description:'View notification template and Go Back', preconditions:'Template exists.', testData:'N/A', testSteps:'1. Login as Maker\n2. Go to Notifications List\n3. Click View on first template\n4. Assert View heading\n5. Click Go Back', expectedResult:'View page opens and Go Back works.', status:'PASS' },
  { tcId:'TC_NOTIF_003', module:'Notification Management', subModule:'Update & Approve', testType:'Positive', description:'Maker updates template, Checker approves, Maker verifies Inactive status', preconditions:'Template exists.', testData:'New body, Status: Inactive, Comment: update approve by checker', testSteps:'1. Login as Maker\n2. Edit first template\n3. Update body and set Inactive\n4. Click Update\n5. Logout\n6. Login as Checker\n7. Review NOTIFICATION UPDATE\n8. Approve\n9. Logout\n10. Login as Maker\n11. Assert Inactive status in list', expectedResult:'Update approved. Maker sees Inactive status.', status:'PASS' },
  { tcId:'TC_NOTIF_004', module:'Notification Management', subModule:'Create & Reject', testType:'Positive', description:'Maker creates template, Checker rejects, Maker acknowledges', preconditions:'', testData:'Rejection comment', testSteps:'1. Maker creates template\n2. Checker rejects\n3. Maker rejects in Maker Pending Process', expectedResult:'Both reject successfully.', status:'PASS' },
  { tcId:'TC_NOTIF_005', module:'Notification Management', subModule:'Update & Reject', testType:'Positive', description:'Maker updates template, Checker rejects, Maker acknowledges', preconditions:'Two templates exist.', testData:'Rejection comments', testSteps:'1. Maker updates 2nd template\n2. Checker rejects\n3. Maker acknowledges', expectedResult:'Both reject successfully.', status:'PASS' },
  { tcId:'TC_NOTIF_006', module:'Notification Management', subModule:'Filter - Event Type', testType:'Positive', description:'Filter by Event Type returns matching templates', preconditions:'Templates with LOGIN_ALERT exist.', testData:'Event Type: LOGIN_ALERT', testSteps:'1. Open Filter\n2. Select LOGIN_ALERT\n3. Apply\n4. Assert LOGIN_ALERT cell visible\n5. Reset', expectedResult:'Matching templates shown.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_001', module:'Notification Management', subModule:'Create - Validation', testType:'Negative', description:'All fields empty shows validation errors', preconditions:'Create form open.', testData:'All fields: (empty)', testSteps:'1. Open Create form\n2. Leave all empty\n3. Click Save\n4. Assert template name required error', expectedResult:'Validation errors shown.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_002', module:'Notification Management', subModule:'Create - Validation', testType:'Negative', description:'Missing template name shows error', preconditions:'', testData:'Name: (empty)', testSteps:'1. Open form\n2. Leave name empty\n3. Fill others\n4. Click Save\n5. Assert "Template name is required"', expectedResult:'"Template name is required" shown.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_003', module:'Notification Management', subModule:'Create - Validation', testType:'Negative', description:'Subject less than 3 chars shows error', preconditions:'', testData:'Subject: AB', testSteps:'1. Open form\n2. Enter "AB" in Subject\n3. Click Save\n4. Assert minimum length error', expectedResult:'Subject length error shown.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_004', module:'Notification Management', subModule:'Create - Validation', testType:'Negative', description:'Missing body shows error', preconditions:'', testData:'Body: (empty)', testSteps:'1. Open form\n2. Leave Body empty\n3. Fill others\n4. Click Save\n5. Assert body required error', expectedResult:'"Body template is required" shown.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_005', module:'Notification Management', subModule:'Create - Validation', testType:'Negative', description:'No Event Type selected shows error', preconditions:'', testData:'Event Type: (not selected)', testSteps:'1. Open form\n2. Fill all except Event Type\n3. Click Save\n4. Assert event type required error', expectedResult:'"Event type is required" shown.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_006', module:'Notification Management', subModule:'Create - Validation', testType:'Negative', description:'No Channel selected shows error', preconditions:'', testData:'Channel: (not selected)', testSteps:'1. Open form\n2. Fill all except Channel\n3. Click Save\n4. Assert channel required error', expectedResult:'"Channel is required" shown.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_007', module:'Notification Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker cannot Approve without comment', preconditions:'Pending NOTIFICATION CREATION.', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review NOTIFICATION CREATION\n3. Click Approve\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm disabled.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_008', module:'Notification Management', subModule:'Approval - Validation', testType:'Negative', description:'Checker cannot Reject without comment', preconditions:'', testData:'Comment: (empty)', testSteps:'1. Login as Checker\n2. Review NOTIFICATION CREATION\n3. Click Reject\n4. Leave comment empty\n5. Assert Confirm disabled', expectedResult:'Confirm disabled.', status:'PASS' },
  { tcId:'TC_NOTIF_NEG_009', module:'Notification Management', subModule:'Filter - Negative', testType:'Negative', description:'Invalid date range shows error', preconditions:'', testData:'From: 31/05/2026, To: 08/05/2026', testSteps:'1. Open Filter\n2. Set From > To date\n3. Apply\n4. Assert date error\n5. Reset', expectedResult:'Date validation error shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // INBOX MAKER PENDING PROCESS
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_INBOX_001', module:'Inbox', subModule:'Maker Pending - Filter', testType:'Positive', description:'Filter by Process ID shows matching record', preconditions:'Process ID 8318490 exists.', testData:'Process ID: 8318490', testSteps:'1. Login as Maker\n2. Go to Inbox > Maker Pending Process\n3. Click Filters\n4. Enter Process ID: 8318490\n5. Apply\n6. Assert cell visible', expectedResult:'Record with Process ID 8318490 shown.', status:'PASS' },
  { tcId:'TC_INBOX_002', module:'Inbox', subModule:'Maker Pending - Filter', testType:'Positive', description:'Filter by Request Type shows matching records', preconditions:'MERCHANT CREATION processes exist.', testData:'Request Type: Merchant Creation', testSteps:'1. Login as Maker\n2. Inbox > Maker Pending Process\n3. Click Filters\n4. Select Merchant Creation\n5. Apply\n6. Assert MERCHANT CREATION cell', expectedResult:'MERCHANT CREATION records shown.', status:'PASS' },
  { tcId:'TC_INBOX_003', module:'Inbox', subModule:'Maker Pending - Filter', testType:'Positive', description:'Filter by Date Range shows records in range', preconditions:'Processes exist in last 2 days.', testData:'From: yesterday, To: today', testSteps:'1. Login as Maker\n2. Inbox > Maker Pending Process\n3. Click Filters\n4. Select From Date: yesterday\n5. Select To Date: today\n6. Apply\n7. Assert table visible', expectedResult:'Records in date range shown.', status:'PASS' },
  { tcId:'TC_INBOX_004', module:'Inbox', subModule:'Maker Pending - Filter', testType:'Positive', description:'Reset Filters clears all values', preconditions:'', testData:'Process ID: 8318490', testSteps:'1. Login as Maker\n2. Apply Process ID filter\n3. Click Reset\n4. Assert Process ID input empty', expectedResult:'Filter cleared.', status:'PASS' },
  { tcId:'TC_INBOX_NEG_001', module:'Inbox', subModule:'Maker Pending - Filter', testType:'Negative', description:'Non-existent Process ID shows No data found', preconditions:'', testData:'Process ID: 934343434343', testSteps:'1. Login as Maker\n2. Inbox > Maker Pending Process\n3. Click Filters\n4. Enter 934343434343\n5. Apply\n6. Assert "No data found"', expectedResult:'"No data found" shown.', status:'PASS' },
  { tcId:'TC_INBOX_NEG_002', module:'Inbox', subModule:'Maker Pending - Filter', testType:'Negative', description:'From Date later than To Date shows validation error', preconditions:'', testData:'From: 31/05/2026, To: 08/05/2026', testSteps:'1. Login as Maker\n2. Inbox > Maker Pending Process\n3. Click Filters\n4. Set From > To date\n5. Apply\n6. Assert "From Date cannot be later"', expectedResult:'Date validation error shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // AUDIT LOGS
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_AUDITLOG_001', module:'Audit Logs', subModule:'View & Filter', testType:'Positive', description:'AdminChecker login captured and verified in Audit Logs', preconditions:'AdminMaker and AdminChecker active.', testData:'Action Type: LOGIN, Username: AdminChecker', testSteps:'1. Login as AdminMaker\n2. Go to Audit Logs\n3. Filter by Action: LOGIN, Username: AdminChecker\n4. Login as AdminChecker in separate session\n5. Refresh\n6. Verify AdminChecker LOGIN row\n7. Click View Details', expectedResult:'AdminChecker LOGIN entry visible with correct data.', status:'PASS' },
  { tcId:'TC_AUDITLOG_002', module:'Audit Logs', subModule:'Filter - Action Type', testType:'Positive', description:'Filter by Action Type LOGIN returns matching results', preconditions:'', testData:'Action Type: LOGIN', testSteps:'1. Click Filter\n2. Select Action Type: LOGIN\n3. Apply\n4. Assert LOGIN rows visible', expectedResult:'LOGIN rows shown.', status:'PASS' },
  { tcId:'TC_AUDITLOG_003', module:'Audit Logs', subModule:'Filter - Username', testType:'Positive', description:'Filter by Username returns matching results', preconditions:'', testData:'Username: AdminMaker', testSteps:'1. Enter AdminMaker in username field\n2. Apply\n3. Assert AdminMaker rows', expectedResult:'AdminMaker rows shown.', status:'PASS' },
  { tcId:'TC_AUDITLOG_004', module:'Audit Logs', subModule:'Filter - Date', testType:'Positive', description:'Filter by date range returns logs in range', preconditions:'', testData:'From: today, To: today', testSteps:'1. Select today in From and To date\n2. Apply\n3. Assert May 2026 rows', expectedResult:'Today logs shown.', status:'PASS' },
  { tcId:'TC_AUDITLOG_005', module:'Audit Logs', subModule:'Filter - Quick Select', testType:'Positive', description:'Quick select Today shows today logs', preconditions:'', testData:'Quick: Today', testSteps:'1. Click Today quick select\n2. Apply\n3. Assert today rows', expectedResult:'Today logs shown.', status:'PASS' },
  { tcId:'TC_AUDITLOG_006', module:'Audit Logs', subModule:'Filter - Reset', testType:'Positive', description:'Reset clears filter and shows all logs', preconditions:'', testData:'Username: AdminMaker (applied)', testSteps:'1. Apply username filter\n2. Reset\n3. Assert input empty\n4. Assert table has rows', expectedResult:'Filter cleared. All logs shown.', status:'PASS' },
  { tcId:'TC_AUDITLOG_NEG_001', module:'Audit Logs', subModule:'Filter - Negative', testType:'Negative', description:'Non-existent username shows No data found', preconditions:'', testData:'Username: jkejke9998', testSteps:'1. Enter jkejke9998 in username\n2. Apply\n3. Assert "No data found"', expectedResult:'"No data found" shown.', status:'PASS' },
  { tcId:'TC_AUDITLOG_NEG_002', module:'Audit Logs', subModule:'Filter - Negative', testType:'Negative', description:'To Date earlier than From Date — no validation error (bug)', preconditions:'', testData:'From: 07/05/2026, To: 01/05/2026', testSteps:'1. Set From: May 7\n2. Set To: May 1\n3. Apply\n4. Assert date range validation error', expectedResult:'Date validation error should be shown.', status:'FAIL' },

  // ══════════════════════════════════════════════════════════════════════════
  // REPORTS
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_RPT_001', module:'Reports', subModule:'Transaction Summary', testType:'Positive', description:'Transaction Summary Report generates successfully with AXIAN aggregator filter', preconditions:'AdminMaker logged into MMP. Jasper accessible via Reports link.', testData:'AGGREGATOR: AXIAN\nFROM_DATE: April 1, 2026\nTO_DATE: Now', testSteps:'1. Login as AdminMaker\n2. Click Reports → Jasper popup\n3. Login to Jasper\n4. Select Transaction_Summary_Report\n5. Set FROM=April 1, TO=Now\n6. Apply\n7. Assert title & timestamp', expectedResult:'"Merchant Transaction Summary" visible. Today date in timestamp.', status:'PASS' },
  { tcId:'TC_RPT_002', module:'Reports', subModule:'Transaction Detail', testType:'Positive', description:'Transaction Detail Report generates with MID, Aggregator, Status and Category filters', preconditions:'Jasper session active from TC_RPT_001.', testData:'MID: 000921773937631\nAGGREGATOR: AXIAN\nSTATUS: ALL\nCATEGORY: SEND_MONEY\nFROM: April 1, TO: Now', testSteps:'1. Close previous report\n2. Select Transaction_Detail_Report\n3. Fill filters\n4. Apply\n5. Assert title, columns, filter values', expectedResult:'"Merchant Transaction Report" visible. MID, AXIAN, SEND_MONEY, SUCCESS columns shown.', status:'PASS' },
  { tcId:'TC_RPT_003', module:'Reports', subModule:'Pending Payments', testType:'Positive', description:'Pending Payments Report generates successfully with valid date range', preconditions:'Jasper session active.', testData:'FROM_DATE: April 1, 2026\nTO_DATE: Now', testSteps:'1. Close previous report\n2. Select Pending_Payments_Report\n3. Set dates\n4. Apply\n5. Assert title and Pending Count column', expectedResult:'"Pending Amounts & Aging Report" visible. "Pending Count" column shown.', status:'PASS' },
  { tcId:'TC_RPT_004', module:'Reports', subModule:'Failed Payments', testType:'Positive', description:'Failed Payments Report generates with Aggregator and Merchant filters set to ALL', preconditions:'Jasper session active.', testData:'AGGREGATOR: ALL\nMERCHANT: ALL\nFROM: April 1, TO: Now', testSteps:'1. Close previous report\n2. Select Failed_Payments_Report\n3. Set dates, confirm ALL filters\n4. Apply\n5. Assert title', expectedResult:'"Merchant Failure Analysis" visible. Timestamp matches today.', status:'PASS' },
  { tcId:'TC_RPT_005', module:'Reports', subModule:'Audit Logs', testType:'Positive', description:'Audit Logs Report generates successfully with valid start and end dates', preconditions:'Jasper session active.', testData:'STARTDATE: April 2026\nENDDATE: Now\nSTATUS: ALL', testSteps:'1. Close previous report\n2. Select Audit Logs\n3. Set STARTDATE month=3, ENDDATE=Now\n4. Select STATUS=ALL\n5. Apply\n6. Assert title', expectedResult:'"System Audit Log Report" visible. Timestamp matches today.', status:'PASS' },
  { tcId:'TC_RPT_NEG_001', module:'Reports', subModule:'Jasper Login', testType:'Negative', description:'Jasper login fails with invalid credentials', preconditions:'AdminMaker logged into MMP. Jasper popup opened.', testData:'Username: fakeuser\nPassword: fakepass', testSteps:'1. Login to Jasper with invalid creds\n2. Assert login button still visible\n3. Assert error message shown\n4. Assert Reports panel NOT visible', expectedResult:'Login rejected. Error message shown. Reports panel not accessible.', status:'PASS' },
  { tcId:'TC_RPT_NEG_002', module:'Reports', subModule:'Transaction Summary', testType:'Negative', description:'FROM date after TO date — no validation error shown (known bug)', preconditions:'Jasper session active.', testData:'FROM_DATE: May 7, 2026\nTO_DATE: April 1, 2026', testSteps:'1. Select Transaction_Summary_Report\n2. Set FROM > TO\n3. Apply\n4. Assert validation error', expectedResult:'Date range validation error shown.', status:'FAIL' },
  { tcId:'TC_RPT_NEG_003', module:'Reports', subModule:'Transaction Detail', testType:'Negative', description:'Invalid MID format (special chars) — no validation error shown (known bug)', preconditions:'Jasper session active.', testData:'MID: 000921773937631111@@@', testSteps:'1. Select Transaction_Detail_Report\n2. Enter invalid MID\n3. Apply\n4. Assert MID format error', expectedResult:'MID format validation error shown.', status:'FAIL' },
  { tcId:'TC_RPT_NEG_004', module:'Reports', subModule:'Audit Logs', testType:'Negative', description:'Audit Logs: Apply without mandatory dates shows field error', preconditions:'Jasper session active.', testData:'STARTDATE: (empty)\nENDDATE: (empty)', testSteps:'1. Select Audit Logs\n2. Leave dates empty\n3. Apply\n4. Assert mandatory field error', expectedResult:'"This field is mandatory so you must enter data." shown for both date fields.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // MERCHANT ONBOARDING - LIMIT PROFILE
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_LIMIT_001', module:'Merchant Onboarding', subModule:'Limit Profile - Create', testType:'Positive', description:'Create limit profile and checker approves', preconditions:'Maker and Checker active.', testData:'Profile Name: auto limit profile, Rule: OUTGOING+AMOUNT+Daily+Min10+Max50+TZS, Comment: approved', testSteps:'1. Login as Maker\n2. Merchant Onboarding > Limit Profile List\n3. Click Add\n4. Fill profile and add rule\n5. Save\n6. Logout\n7. Login as Checker\n8. Review LIMIT DEFINITION CREATION\n9. Approve', expectedResult:'Created and approved.', status:'PASS' },
  { tcId:'TC_LIMIT_002', module:'Merchant Onboarding', subModule:'Limit Profile - View', testType:'Positive', description:'View limit profile and Go Back', preconditions:'Approved profile exists.', testData:'N/A', testSteps:'1. Login as Maker\n2. Limit Profile List\n3. Click View on first row\n4. Assert View Limit Profile heading\n5. Click Go Back', expectedResult:'View page opens. Go Back returns to list.', status:'PASS' },
  { tcId:'TC_LIMIT_003', module:'Merchant Onboarding', subModule:'Limit Profile - Update', testType:'Positive', description:'Update limit profile and checker approves', preconditions:'Profile exists.', testData:'Updated name, Min 50, Max 500, Comment: update approve', testSteps:'1. Login as Maker\n2. Edit first profile\n3. Update name and rule\n4. Submit\n5. Logout\n6. Login as Checker\n7. Review LIMIT DEFINITION UPDATE\n8. Approve', expectedResult:'Update approved.', status:'PASS' },
  { tcId:'TC_LIMIT_004', module:'Merchant Onboarding', subModule:'Limit Profile - Reject', testType:'Negative', description:'Checker rejects update, maker rejects in Maker Pending', preconditions:'Update request in Checker queue.', testData:'Checker comment: reject update, Maker comment: reject approve by maker', testSteps:'1. Login as Checker\n2. Review LIMIT DEFINITION UPDATE\n3. Reject\n4. Logout\n5. Login as Maker\n6. Inbox > Maker Pending\n7. Review LIMIT DEFINITION UPDATE\n8. Reject', expectedResult:'Both reject successfully.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_001', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Positive', description:'Filter by Profile Name returns matching profiles', preconditions:'Profiles with "auto" in name exist.', testData:'Profile Name: auto', testSteps:'1. Login as Maker\n2. Limit Profile List\n3. Click Filter\n4. Enter "auto"\n5. Apply\n6. Assert table\n7. Reset', expectedResult:'Matching profiles shown.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_002', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Positive', description:'Filter by Status Active returns active profiles', preconditions:'Active profiles exist.', testData:'Status: Active', testSteps:'1. Open Filter\n2. Select Active\n3. Apply\n4. Assert ACTIVE cell\n5. Reset', expectedResult:'Active profiles shown.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_003', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Positive', description:'Quick select Today filters correctly', preconditions:'', testData:'Quick: Today', testSteps:'1. Open Filter\n2. Click Today\n3. Assert table or no data\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_004', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Positive', description:'Quick select Last 7 days filters correctly', preconditions:'', testData:'Quick: Last 7 days', testSteps:'1. Open Filter\n2. Click Last 7 days\n3. Assert table or no data\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_005', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Positive', description:'Quick select This month filters correctly', preconditions:'', testData:'Quick: This month', testSteps:'1. Open Filter\n2. Click This month\n3. Assert table or no data\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_006', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Positive', description:'Reset clears all limit profile filter inputs', preconditions:'', testData:'Name: auto (applied)', testSteps:'1. Open Filter\n2. Enter "auto"\n3. Apply\n4. Reset\n5. Assert input empty', expectedResult:'Filter cleared.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_NEG_001', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Negative', description:'Non-existent name shows No data found', preconditions:'', testData:'Name: zzz_nonexistent_999', testSteps:'1. Open Filter\n2. Enter zzz_nonexistent_999\n3. Apply\n4. Assert "No data found"\n5. Reset', expectedResult:'"No data found" shown.', status:'PASS' },
  { tcId:'TC_LIMIT_FILTER_NEG_002', module:'Merchant Onboarding', subModule:'Limit Profile - Filter', testType:'Negative', description:'From Date later than To Date shows validation error', preconditions:'', testData:'From: 31/05/2026, To: 08/05/2026', testSteps:'1. Open Filter\n2. Set From > To\n3. Apply\n4. Assert date error\n5. Reset', expectedResult:'Date error shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // MERCHANT ONBOARDING - MDR PROFILE
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_MDR_001', module:'Merchant Onboarding', subModule:'MDR Profile - Create', testType:'Positive', description:'Create MDR profile and checker approves', preconditions:'Maker and Checker active.', testData:'Name: auto mdr profile, Category: Carpentry contractors, Method: QR, Rule: MDR10+Min10+Max100, Comment: mdr approved', testSteps:'1. Login as Maker\n2. MDR Profile List\n3. Click Add\n4. Fill profile, select category and method\n5. Add rule\n6. Save\n7. Logout\n8. Login as Checker\n9. Review MDR PROFILE CREATION\n10. Approve', expectedResult:'Created and approved.', status:'PASS' },
  { tcId:'TC_MDR_002', module:'Merchant Onboarding', subModule:'MDR Profile - Update', testType:'Positive', description:'Update MDR profile and checker approves', preconditions:'MDR profile exists.', testData:'Updated values, Comment: mdr update approved', testSteps:'1. Login as Maker\n2. Edit first MDR profile\n3. Update values\n4. Submit\n5. Logout\n6. Login as Checker\n7. Review MDR PROFILE UPDATE\n8. Approve', expectedResult:'Update approved.', status:'PASS' },
  { tcId:'TC_MDR_003', module:'Merchant Onboarding', subModule:'MDR Profile - Reject', testType:'Negative', description:'Checker rejects MDR update, maker rejects in Maker Pending', preconditions:'MDR update in Checker queue.', testData:'Comments for both', testSteps:'1. Login as Checker\n2. Reject MDR PROFILE UPDATE\n3. Logout\n4. Login as Maker\n5. Reject in Maker Pending', expectedResult:'Both reject successfully.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_001', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Positive', description:'Filter by Profile Name returns matching MDR profiles', preconditions:'', testData:'Name: auto', testSteps:'1. Open Filter\n2. Enter "auto"\n3. Apply\n4. Assert table\n5. Reset', expectedResult:'Matching MDR profiles shown.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_002', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Positive', description:'Filter by Status Active returns active MDR profiles', preconditions:'', testData:'Status: Active', testSteps:'1. Open Filter\n2. Select Active\n3. Apply\n4. Assert ACTIVE\n5. Reset', expectedResult:'Active profiles shown.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_003', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Positive', description:'Quick select Today filters MDR profiles', preconditions:'', testData:'Quick: Today', testSteps:'1. Open Filter\n2. Click Today\n3. Assert results\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_004', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Positive', description:'Quick select Last 7 days filters MDR profiles', preconditions:'', testData:'Quick: Last 7 days', testSteps:'1. Open Filter\n2. Click Last 7 days\n3. Assert results\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_005', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Positive', description:'Quick select Last 30 days filters MDR profiles', preconditions:'', testData:'Quick: Last 30 days', testSteps:'1. Open Filter\n2. Click Last 30 days\n3. Assert results\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_006', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Positive', description:'Reset clears MDR filter inputs', preconditions:'', testData:'Name: auto (applied)', testSteps:'1. Open Filter\n2. Enter "auto"\n3. Apply\n4. Reset\n5. Assert input empty', expectedResult:'Filter cleared.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_NEG_001', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Negative', description:'Non-existent MDR name shows No data found', preconditions:'', testData:'Name: zzz_nonexistent_mdr_999', testSteps:'1. Open Filter\n2. Enter zzz_nonexistent_mdr_999\n3. Apply\n4. Assert "No data found"\n5. Reset', expectedResult:'"No data found" shown.', status:'PASS' },
  { tcId:'TC_MDR_FILTER_NEG_002', module:'Merchant Onboarding', subModule:'MDR Profile - Filter', testType:'Negative', description:'Invalid date range shows error for MDR', preconditions:'', testData:'From: 31/05/2026, To: 08/05/2026', testSteps:'1. Open Filter\n2. Set From > To\n3. Apply\n4. Assert date error\n5. Reset', expectedResult:'Date error shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // MERCHANT ONBOARDING - TAX PROFILE
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_TAX_001', module:'Merchant Onboarding', subModule:'Tax Profile - Create', testType:'Positive', description:'Create Tax profile and checker approves', preconditions:'Maker and Checker active.', testData:'Name: Auto tax profile, Region: Arusha, Rule: Tax20+Min100+Max500, Comment: tax profile approved', testSteps:'1. Login as Maker\n2. Tax Profile List\n3. Click Add\n4. Fill name and region\n5. Add tax rule\n6. Save\n7. Logout\n8. Login as Checker\n9. Review TAX PROFILE CREATION\n10. Approve', expectedResult:'Created and approved.', status:'PASS' },
  { tcId:'TC_TAX_002', module:'Merchant Onboarding', subModule:'Tax Profile - Update', testType:'Positive', description:'Update Tax profile and checker approves', preconditions:'Tax profile exists.', testData:'Updated values, Comment: tax update approved', testSteps:'1. Login as Maker\n2. Edit first tax profile\n3. Update values\n4. Submit\n5. Logout\n6. Login as Checker\n7. Review TAX PROFILE UPDATE\n8. Approve', expectedResult:'Update approved.', status:'PASS' },
  { tcId:'TC_TAX_003', module:'Merchant Onboarding', subModule:'Tax Profile - Reject', testType:'Negative', description:'Checker rejects Tax update, maker rejects in Maker Pending', preconditions:'Tax update in Checker queue.', testData:'Comments for both', testSteps:'1. Login as Checker\n2. Reject TAX PROFILE UPDATE\n3. Logout\n4. Login as Maker\n5. Reject in Maker Pending', expectedResult:'Both reject successfully.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_001', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Positive', description:'Filter by Profile Name returns matching Tax profiles', preconditions:'', testData:'Name: Auto', testSteps:'1. Open Filter\n2. Enter "Auto"\n3. Apply\n4. Assert table\n5. Reset', expectedResult:'Matching profiles shown.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_002', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Positive', description:'Filter by Region Arusha returns profiles in that region', preconditions:'Arusha profiles exist.', testData:'Region: Arusha', testSteps:'1. Open Filter\n2. Enter "Arusha" in Region\n3. Apply\n4. Assert Arusha cell\n5. Reset', expectedResult:'Arusha profiles shown.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_003', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Positive', description:'Filter by Status Active returns active Tax profiles', preconditions:'', testData:'Status: Active', testSteps:'1. Open Filter\n2. Select Active\n3. Apply\n4. Assert ACTIVE\n5. Reset', expectedResult:'Active profiles shown.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_004', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Positive', description:'Quick select Today filters Tax profiles', preconditions:'', testData:'Quick: Today', testSteps:'1. Open Filter\n2. Click Today\n3. Assert results\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_005', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Positive', description:'Quick select This month filters Tax profiles', preconditions:'', testData:'Quick: This month', testSteps:'1. Open Filter\n2. Click This month\n3. Assert results\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_006', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Positive', description:'Quick select Last 30 days filters Tax profiles', preconditions:'', testData:'Quick: Last 30 days', testSteps:'1. Open Filter\n2. Click Last 30 days\n3. Assert results\n4. Reset', expectedResult:'Filter applied.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_007', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Positive', description:'Reset clears all Tax filter inputs', preconditions:'', testData:'Name: Auto, Region: Arusha (applied)', testSteps:'1. Open Filter\n2. Enter name and region\n3. Apply\n4. Reset\n5. Assert both inputs empty', expectedResult:'All filters cleared.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_NEG_001', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Negative', description:'Non-existent Tax name shows No data found', preconditions:'', testData:'Name: zzz_nonexistent_tax_999', testSteps:'1. Open Filter\n2. Enter zzz_nonexistent_tax_999\n3. Apply\n4. Assert "No data found"\n5. Reset', expectedResult:'"No data found" shown.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_NEG_002', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Negative', description:'Non-existent region shows No data found', preconditions:'', testData:'Region: zzz_nonexistent_region_999', testSteps:'1. Open Filter\n2. Enter zzz_nonexistent_region_999\n3. Apply\n4. Assert "No data found"\n5. Reset', expectedResult:'"No data found" shown.', status:'PASS' },
  { tcId:'TC_TAX_FILTER_NEG_003', module:'Merchant Onboarding', subModule:'Tax Profile - Filter', testType:'Negative', description:'Invalid date range shows error for Tax', preconditions:'', testData:'From: 31/05/2026, To: 08/05/2026', testSteps:'1. Open Filter\n2. Set From > To\n3. Apply\n4. Assert date error\n5. Reset', expectedResult:'Date error shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // ROLE CREATION - ADDITIONAL CASES (from Role_Creation_Report)
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_ROLE_NEG_008', module:'User & Role Management', subModule:'Role - Validation', testType:'Negative', description:'Valid name and description but no permissions selected — shows permission error', preconditions:'AdminMaker logged in. Add Role form is open.', testData:'Name: ValidName, Description: ValidDesc, Permissions: none', testSteps:'1. Login as AdminMaker\n2. Open Add Role form\n3. Fill valid Name\n4. Fill valid Description\n5. Do NOT select any permission\n6. Click Save\n7. Assert "Please select at least one permission"\n8. Assert "Processed OK" is NOT visible', expectedResult:'Permission required error shown even when name and description are valid.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_009', module:'User & Role Management', subModule:'Role - Approval Validation', testType:'Negative', description:'Checker cannot Approve role without a comment — Confirm button is disabled', preconditions:'A role has been submitted by AdminMaker and is pending approval.', testData:'Approval Comment: (empty)', testSteps:'1. AdminMaker creates a role\n2. Logout AdminMaker\n3. Login as AdminChecker\n4. Go to Inbox > Pending Processes\n5. Click Review on pending role\n6. Click Approve\n7. Leave comment empty\n8. Assert Confirm button is disabled', expectedResult:'Confirm button is disabled. Approval cannot proceed.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_010', module:'User & Role Management', subModule:'Role - Approval Validation', testType:'Negative', description:'Checker cannot Reject role without a comment — Confirm button is disabled', preconditions:'A role has been submitted by AdminMaker and is pending approval.', testData:'Rejection Comment: (empty)', testSteps:'1. AdminMaker creates a role\n2. Logout AdminMaker\n3. Login as AdminChecker\n4. Go to Inbox > Pending Processes\n5. Click Review on pending role\n6. Click Reject\n7. Leave comment empty\n8. Assert Confirm button is disabled', expectedResult:'Confirm button is disabled. Rejection cannot proceed.', status:'PASS' },
  { tcId:'TC_ROLE_NEG_011', module:'User & Role Management', subModule:'Role - Approval Validation', testType:'Negative', description:'Checker rejects role creation with valid rejection reason', preconditions:'A role has been submitted by AdminMaker and is pending approval.', testData:'Rejection Comment: Rejected by AdminChecker - Automation Test', testSteps:'1. AdminMaker creates a role\n2. Logout AdminMaker\n3. Login as AdminChecker\n4. Go to Inbox > Pending Processes\n5. Click Review on pending role\n6. Click Reject\n7. Enter rejection comment\n8. Click Confirm\n9. Assert "Process rejected successfully" toast\n10. Logout AdminChecker', expectedResult:'Role creation rejected. "Process rejected successfully" toast shown.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // MERCHANT ONBOARDING - FUNCTIONAL FLOWS (from Merchant_Onboarding_TestCases)
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_MO_001', module:'Merchant Onboarding', subModule:'Merchant - Machinga Flow', testType:'Positive', description:'Machinga merchant onboarding completes successfully with valid data and document upload', preconditions:'Maker (Labesh_Maker) is registered in MMP. Test assets (image.jpg, document.pdf) exist under test-assets/.', testData:'Merchant Type: Machinga | ID Type: MSISDN | Mobile: 658281034 | Role: Partner | Last Name: MachingaTest | Email: machinga1@yopmail.com | Category: Special trade contractors | Business Name: Machinga Biz Co | Documents: image.jpg (Business License), document.pdf (VAT Certificate)', testSteps:'1. Login as Labesh_Maker\n2. Merchant Onboarding > Merchant List > Add Merchant\n3. Select QR, Merchant Type = Machinga, ID Type = MSISDN, mobile 658281034\n4. Click Proceed to Form\n5. Fill all merchant form fields\n6. Upload image.jpg as Business License, document.pdf as VAT Certificate\n7. Click Submit Merchant then Close\n8. Logout\n9. Re-login as Labesh_Maker\n10. Verify "STEVEN MachingaTest" in Merchant List', expectedResult:'Merchant onboarding form loads. Both documents upload successfully. Merchant "STEVEN MachingaTest" visible in Merchant List.', status:'PASS' },
  { tcId:'TC_MO_002', module:'Merchant Onboarding', subModule:'Merchant - Company Flow', testType:'Positive', description:'Company merchant onboarding completes end-to-end with Checker approval and merchant visible in list', preconditions:'Maker (Labesh_Maker) and Checker (LabeshChecker) accounts are active. Test assets exist.', testData:'Merchant Type: Company | ID Type: MSISDN | Mobile: 658281034 | Role: Employee | Last Name: CompanyMerchant | Email: comp2@yopmail.com | Category: Carpentry contractors | Business Name: Company Biz Solutions | TIN: 999999 | VAT: VT_98889 | Documents: 5 files', testSteps:'1. Login as Labesh_Maker\n2. Add Merchant: Company, MSISDN, mobile 658281034\n3. Fill all fields including TIN, VAT, Certificate of Incorporation\n4. Upload 5 documents\n5. Submit Merchant\n6. Logout\n7. Login as LabeshChecker\n8. Inbox > Pending Processes > Review MERCHANT CREATION\n9. Approve with comment "approved by checker"\n10. Logout\n11. Re-login as Labesh_Maker\n12. Verify "CompanyMerchant" in Merchant List', expectedResult:'All 5 documents upload successfully. Checker approves. "CompanyMerchant" visible in Merchant List.', status:'PASS' },
  { tcId:'TC_MO_003', module:'Merchant Onboarding', subModule:'Merchant - Individual Flow', testType:'Positive', description:'Individual merchant onboarding completes end-to-end with Checker approval and merchant verified in list', preconditions:'Maker (Labesh_Maker) and Checker (LabeshChecker) are active. Test asset image.jpg exists.', testData:'Merchant Type: Individual | ID Type: MSISDN | Mobile: 658281034 | Last Name: IndividualTest | Email: indi1@yopmail.com | Category: Roofing and siding contractors | Business Name: Individual Biz Co | Document: image.jpg', testSteps:'1. Login as Labesh_Maker\n2. Add Merchant: Individual, MSISDN, mobile 658281034\n3. Fill all form fields\n4. Upload image.jpg\n5. Submit Merchant\n6. Logout\n7. Login as LabeshChecker\n8. Review MERCHANT CREATION > Approve with comment\n9. Logout\n10. Re-login as Labesh_Maker\n11. Verify "IndividualTest" in Merchant List', expectedResult:'Document uploads successfully. Checker approves. "IndividualTest" visible in Merchant List.', status:'PASS' },
  { tcId:'TC_MO_004', module:'Merchant Onboarding', subModule:'Merchant - NIDA Flow', testType:'Positive', description:'NIDA registered merchant onboarding completes with submission success message, Checker approval, and merchant visible in list', preconditions:'Maker and Checker are active. NIDA merchant type is available.', testData:'Merchant Type: NIDA Registered | ID Type: MSISDN | Mobile: 658281034 | Role: Owner | Last Name: AssertMerchant | Email: nidaassert2@yopmail.com | Business Name: Assert Business Co', testSteps:'1. Login as Labesh_Maker\n2. Add Merchant: NIDA Registered, MSISDN, mobile 658281034\n3. Fill all form fields\n4. Submit Merchant\n5. Verify "Processed OK Process ID:" message\n6. Logout\n7. Login as LabeshChecker\n8. Review MERCHANT CREATION > Approve with comment\n9. Logout\n10. Re-login as Labesh_Maker\n11. Verify "AssertMerchant" in Merchant List', expectedResult:'"Processed OK Process ID:" shown. Checker approves. "AssertMerchant" visible in Merchant List.', status:'PASS' },
  { tcId:'TC_MO_005', module:'Merchant Onboarding', subModule:'Login - Validation', testType:'Negative', description:'Login fails when invalid credentials are entered', preconditions:'MMP login page is accessible.', testData:'Username: Labesh_Maker | Password: WrongPassword@999', testSteps:'1. Navigate to https://mixxmmp-test.tigo.co.tz/login\n2. Enter username: Labesh_Maker\n3. Enter password: WrongPassword@999\n4. Click Sign In\n5. Assert login rejected', expectedResult:'Login is rejected. Error message displayed. User remains on login page.', status:'PASS' },
  { tcId:'TC_MO_006', module:'Merchant Onboarding', subModule:'Config - Validation', testType:'Negative', description:'Proceed to Form is blocked when mobile number field is left empty', preconditions:'Maker is logged in. Add Merchant dialog is open.', testData:'Product: QR | Merchant Type: Individual | ID Type: MSISDN | Mobile Number: (empty)', testSteps:'1. Login as Labesh_Maker\n2. Navigate to Merchant Onboarding > Merchant List > Add Merchant\n3. Select QR, Individual, MSISDN\n4. Leave mobile number empty\n5. Click Proceed to Form\n6. Assert validation error', expectedResult:'Form does not advance. Validation error: "Mobile number is required".', status:'PASS' },
  { tcId:'TC_MO_007', module:'Merchant Onboarding', subModule:'Config - Validation', testType:'Negative', description:'Proceed to Form is blocked when mobile number has invalid format', preconditions:'Maker is logged in. Add Merchant dialog is open.', testData:'Product: QR | Merchant Type: Individual | ID Type: MSISDN | Mobile Number: 123', testSteps:'1. Login as Labesh_Maker\n2. Navigate to Add Merchant\n3. Select QR, Individual, MSISDN\n4. Enter mobile: 123\n5. Click Proceed to Form\n6. Assert validation error', expectedResult:'Form does not advance. Validation error for invalid mobile number format.', status:'PASS' },
  { tcId:'TC_MO_008', module:'Merchant Onboarding', subModule:'Form - Validation', testType:'Negative', description:'Submit Merchant is blocked when mandatory form fields are left empty', preconditions:'Maker is logged in. Config selected. Proceed to Form clicked.', testData:'All required fields: (empty)', testSteps:'1. Login as Labesh_Maker\n2. Navigate to Add Merchant, select config, click Proceed to Form\n3. Leave all required fields blank\n4. Click Submit Merchant\n5. Assert submission blocked and validation errors shown', expectedResult:'Submission blocked. All empty required fields highlighted. No merchant created.', status:'PASS' },
  { tcId:'TC_MO_009', module:'Merchant Onboarding', subModule:'Form - Validation', testType:'Negative', description:'Submit Merchant is blocked when an invalid email format is entered', preconditions:'Maker is logged in. Proceed to Form completed for Individual merchant.', testData:'Last Name: TestUser | Email: not-a-valid-email | Other fields: valid', testSteps:'1. Login as Labesh_Maker, navigate to Add Merchant\n2. Complete config and click Proceed to Form\n3. Fill all fields but enter email: not-a-valid-email\n4. Click Submit Merchant\n5. Assert email validation error', expectedResult:'Submission blocked. Email field shows validation error.', status:'PASS' },
  { tcId:'TC_MO_010', module:'Merchant Onboarding', subModule:'Form - Validation', testType:'Negative', description:'Submit Merchant is blocked when license expiry date is set in the past', preconditions:'Maker is logged in. Proceed to Form completed for Individual merchant.', testData:'License Expiry Date: January 1, 2020 (past) | All other fields: valid', testSteps:'1. Login as Labesh_Maker, navigate to Add Merchant\n2. Complete config and click Proceed to Form\n3. Fill all valid fields\n4. Set License Expiry Date to Jan 1, 2020\n5. Click Submit Merchant\n6. Assert date error', expectedResult:'Submission blocked. License Expiry Date shows error: "Date must be in the future".', status:'PASS' },
  { tcId:'TC_MO_011', module:'Merchant Onboarding', subModule:'Documents - Validation', testType:'Negative', description:'Document upload is rejected when an unsupported file type is uploaded', preconditions:'Maker is logged in. Merchant form filled. Documents section is open.', testData:'File: test-file.exe (unsupported type)', testSteps:'1. Login as Labesh_Maker, navigate to Add Merchant\n2. Complete config and form steps\n3. Click Documents tab\n4. Click "Upload a file" and select a .exe file\n5. Assert upload rejected', expectedResult:'Upload rejected. Error: "Unsupported file type. Please upload a PDF or image file."', status:'PASS' },
  { tcId:'TC_MO_012', module:'Merchant Onboarding', subModule:'Checker - Reject Flow', testType:'Negative', description:'Checker rejects merchant — merchant should not appear as active in Merchant List', preconditions:'Maker has submitted a merchant. Checker (LabeshChecker) is logged in. Entry visible in Pending Processes.', testData:'Checker comment: "Rejected - incomplete business details" | Action: Reject', testSteps:'1. Login as LabeshChecker\n2. Navigate to Inbox > Pending Processes\n3. Verify MERCHANT CREATION entry visible\n4. Click Review\n5. Click Reject\n6. Enter comment: "Rejected - incomplete business details"\n7. Click Confirm\n8. Logout as Checker\n9. Login as Labesh_Maker, navigate to Merchant List\n10. Search for the rejected merchant', expectedResult:'"Process rejected successfully" shown. Rejected merchant does not appear as active in Merchant List.', status:'PASS' },

  // ══════════════════════════════════════════════════════════════════════════
  // ROLE UPDATE
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_ROLE_UPD_E2E_001', module:'User & Role Management', subModule:'Role Update & Approve', testType:'Positive', description:'Full E2E role update and approval flow', preconditions:'At least one role exists. AdminMaker & AdminChecker active.', testData:'Updated Name: Auto_Role_Update_<ts>\nUpdated Description: Updated role description at <ts>\nComment: Approved by AdminChecker - Automation Test', testSteps:'1. Login as AdminMaker\n2. Go to User & Role Management → Role List\n3. Click Edit on first role\n4. Clear Name and fill with unique updated name\n5. Clear Description and fill with unique updated description\n6. Save and verify "Processed OK"\n7. Logout\n8. Login as AdminChecker\n9. Go to Inbox → Pending Processes\n10. Click ROLE UPDATE row\n11. Click Review\n12. Verify "Review Role" heading\n13. Click Approve, enter comment, Confirm\n14. Verify "Process approved successfully"\n15. Logout', expectedResult:'"Processed OK" on update. "Process approved successfully" on approval.', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_001', module:'User & Role Management', subModule:'Role Update - Validation', testType:'Negative', description:'Clear Role Name shows "Name must be at least 4 characters"', preconditions:'Edit Role form is open.', testData:'Role Name: (cleared)', testSteps:'1. Open Edit Role form\n2. Clear Role Name\n3. Click Save\n4. Assert "Name must be at least 4 characters"\n5. Assert "Processed OK" NOT visible', expectedResult:'"Name must be at least 4 characters" shown. No update submitted.', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_002', module:'User & Role Management', subModule:'Role Update - Validation', testType:'Negative', description:'Role Name too short (< 4 chars) shows validation error', preconditions:'Edit Role form is open.', testData:'Role Name: abc (3 chars)', testSteps:'1. Open Edit Role form\n2. Clear Name and type "abc"\n3. Click Save\n4. Assert "Name must be at least 4 characters"', expectedResult:'"Name must be at least 4 characters" shown.', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_003', module:'User & Role Management', subModule:'Role Update - Validation', testType:'Negative', description:'Role Name too long (> 70 chars) — max length enforcement', preconditions:'Edit Role form is open.', testData:'Role Name: 71 × "A"', testSteps:'1. Open Edit Role form\n2. Clear Name and type 71 "A" characters\n3. Press Tab\n4. Assert either field capped at 70 or error shown', expectedResult:'Field caps at 70 chars or shows "Name cannot exceed 70 characters".', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_004', module:'User & Role Management', subModule:'Role Update - Validation', testType:'Negative', description:'Clear Description shows "Description must be at least 4 characters"', preconditions:'Edit Role form is open.', testData:'Description: (cleared)', testSteps:'1. Open Edit Role form\n2. Clear Description\n3. Click Save\n4. Assert "Description must be at least 4 characters"', expectedResult:'"Description must be at least 4 characters" shown.', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_005', module:'User & Role Management', subModule:'Role Update - Validation', testType:'Negative', description:'Description too short (< 4 chars) shows validation error', preconditions:'Edit Role form is open.', testData:'Description: abc (3 chars)', testSteps:'1. Open Edit Role form\n2. Clear Description and type "abc"\n3. Click Save\n4. Assert "Description must be at least 4 characters"', expectedResult:'"Description must be at least 4 characters" shown.', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_006', module:'User & Role Management', subModule:'Role Update - Approval Validation', testType:'Negative', description:'Checker cannot Approve role update without a comment — Confirm disabled', preconditions:'Pending ROLE UPDATE exists.', testData:'Comment: (empty)', testSteps:'1. Login as AdminChecker\n2. Review ROLE UPDATE\n3. Click Approve\n4. Leave comment empty\n5. Assert Confirm button disabled', expectedResult:'Confirm button disabled. Approval cannot proceed.', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_007', module:'User & Role Management', subModule:'Role Update - Approval Validation', testType:'Negative', description:'Checker cannot Reject role update without a comment — Confirm disabled', preconditions:'Pending ROLE UPDATE exists.', testData:'Comment: (empty)', testSteps:'1. Login as AdminChecker\n2. Review ROLE UPDATE\n3. Click Reject\n4. Leave comment empty\n5. Assert Confirm button disabled', expectedResult:'Confirm button disabled. Rejection cannot proceed.', status:'N/A' },
  { tcId:'TC_ROLE_UPD_NEG_008', module:'User & Role Management', subModule:'Role Update - Approval Validation', testType:'Negative', description:'Checker rejects role update with valid reason', preconditions:'Pending ROLE UPDATE exists.', testData:'Comment: Rejected by AdminChecker - Automation Test: Invalid role details', testSteps:'1. Login as AdminChecker\n2. Review ROLE UPDATE\n3. Click Reject\n4. Enter comment\n5. Click Confirm\n6. Assert "Process rejected"\n7. Logout', expectedResult:'"Process rejected" toast shown. Request removed from Pending Processes.', status:'N/A' },

  // ══════════════════════════════════════════════════════════════════════════
  // USER UPDATE
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_USER_UPD_E2E_001', module:'User & Role Management', subModule:'User Update & Approve', testType:'Positive', description:'Full E2E user update and approval flow', preconditions:'At least one user exists. AdminMaker & AdminChecker active.', testData:'Updated Email: userupdate<ts>@yopmail.com\nComment: Approved by AdminChecker - Automation Test', testSteps:'1. Login as AdminMaker\n2. Go to User & Role Management → User List\n3. Click Edit on first user\n4. Clear Email and fill with unique updated email\n5. Save and verify "Processed OK"\n6. Logout\n7. Login as AdminChecker\n8. Go to Inbox → Pending Processes\n9. Click USER UPDATE row\n10. Click Review\n11. Verify "Review User" heading\n12. Click Approve, enter comment, Confirm\n13. Verify "Process approved successfully"\n14. Logout', expectedResult:'"Processed OK" on update. "Process approved successfully" on approval.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_001', module:'User & Role Management', subModule:'User Update - Validation', testType:'Negative', description:'Clear Email shows "Invalid email format"', preconditions:'Edit User form is open.', testData:'Email: (cleared)', testSteps:'1. Open Edit User form\n2. Clear Email\n3. Click Save\n4. Assert "Invalid email format"', expectedResult:'"Invalid email format" shown.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_002', module:'User & Role Management', subModule:'User Update - Validation', testType:'Negative', description:'Invalid email (missing @) shows "Invalid email format"', preconditions:'Edit User form is open.', testData:'Email: invalidemail.com', testSteps:'1. Open Edit User form\n2. Clear Email and type "invalidemail.com"\n3. Click Save\n4. Assert "Invalid email format"', expectedResult:'"Invalid email format" shown.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_003', module:'User & Role Management', subModule:'User Update - Validation', testType:'Negative', description:'Clear First Name shows "First name is required"', preconditions:'Edit User form is open.', testData:'First Name: (cleared)', testSteps:'1. Open Edit User form\n2. Clear First Name\n3. Click Save\n4. Assert "First name is required"', expectedResult:'"First name is required" shown.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_004', module:'User & Role Management', subModule:'User Update - Validation', testType:'Negative', description:'Clear Last Name shows "Last name is required"', preconditions:'Edit User form is open.', testData:'Last Name: (cleared)', testSteps:'1. Open Edit User form\n2. Clear Last Name\n3. Click Save\n4. Assert "Last name is required"', expectedResult:'"Last name is required" shown.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_005', module:'User & Role Management', subModule:'User Update - Validation', testType:'Negative', description:'Clear Phone shows "Phone number is required"', preconditions:'Edit User form is open.', testData:'Phone: (cleared)', testSteps:'1. Open Edit User form\n2. Clear Phone\n3. Click Save\n4. Assert "Phone number is required"', expectedResult:'"Phone number is required" shown.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_006', module:'User & Role Management', subModule:'User Update - Approval Validation', testType:'Negative', description:'Checker cannot Approve user update without a comment — Confirm disabled', preconditions:'Pending USER UPDATE exists.', testData:'Comment: (empty)', testSteps:'1. Login as AdminChecker\n2. Review USER UPDATE\n3. Click Approve\n4. Leave comment empty\n5. Assert Confirm button disabled', expectedResult:'Confirm button disabled. Approval cannot proceed.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_007', module:'User & Role Management', subModule:'User Update - Approval Validation', testType:'Negative', description:'Checker cannot Reject user update without a comment — Confirm disabled', preconditions:'Pending USER UPDATE exists.', testData:'Comment: (empty)', testSteps:'1. Login as AdminChecker\n2. Review USER UPDATE\n3. Click Reject\n4. Leave comment empty\n5. Assert Confirm button disabled', expectedResult:'Confirm button disabled. Rejection cannot proceed.', status:'N/A' },
  { tcId:'TC_USER_UPD_NEG_008', module:'User & Role Management', subModule:'User Update - Approval Validation', testType:'Negative', description:'Checker rejects user update with valid reason', preconditions:'Pending USER UPDATE exists.', testData:'Comment: Rejected by AdminChecker - Automation Test: Invalid user details', testSteps:'1. Login as AdminChecker\n2. Review USER UPDATE\n3. Click Reject\n4. Enter comment\n5. Click Confirm\n6. Assert "Process rejected"\n7. Logout', expectedResult:'"Process rejected" toast shown. Request removed from Pending Processes.', status:'N/A' },

  // ══════════════════════════════════════════════════════════════════════════
  // INBOX — new TC_INBOX_005
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_INBOX_005', module:'Inbox', subModule:'Maker Pending Process - Filter & Review', testType:'Positive', description:'Filter by Request Type then Review — action buttons Go Back, Reject, Approve are all visible', preconditions:'Labesh_Maker logged in. At least one AGGREGATOR CREATION record in Maker Pending Process.', testData:'Request Type: Aggregator Creation', testSteps:'1. Login as Labesh_Maker\n2. Go to Inbox → Maker Pending Process\n3. Click Filters\n4. Select Request Type: Aggregator Creation\n5. Click Apply Filters\n6. Assert AGGREGATOR CREATION row visible\n7. Click Review on first result\n8. Assert "Review Aggregator" heading visible\n9. Assert Go Back, Reject, Approve buttons visible\n10. Click Go Back\n11. Assert table restored', expectedResult:'Review page opens. Go Back, Reject, Approve all visible. Go Back returns to the list.', status:'N/A' },

  // ══════════════════════════════════════════════════════════════════════════
  // AUDIT LOGS — new TC_AUDITLOG_007 to 012
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_AUDITLOG_007', module:'Audit Logs', subModule:'Action Type Filter', testType:'Positive', description:'Filter by Action Type ALL returns all log records', preconditions:'AdminMaker logged in. Audit Logs page open.', testData:'Action Type: ALL', testSteps:'1. Click Filter\n2. Select Action Type: ALL\n3. Click Apply Filters\n4. Assert at least one row visible', expectedResult:'Table shows all log records. At least one row visible.', status:'N/A' },
  { tcId:'TC_AUDITLOG_008', module:'Audit Logs', subModule:'Action Type Filter', testType:'Positive', description:'Filter by Action Type AGGREGATOR_CREATION returns matching records', preconditions:'AdminMaker logged in. Audit Logs page open.', testData:'Action Type: AGGREGATOR_CREATION', testSteps:'1. Click Filter\n2. Select Action Type: AGGREGATOR_CREATION\n3. Click Apply Filters\n4. If rows visible: assert badge = AGGREGATOR_CREATION\n5. If no data: assert "No data found"', expectedResult:'Only AGGREGATOR_CREATION rows shown, or "No data found".', status:'N/A' },
  { tcId:'TC_AUDITLOG_009', module:'Audit Logs', subModule:'Action Type Filter', testType:'Positive', description:'Filter by Action Type AGGREGATOR_UPDATE returns matching records', preconditions:'AdminMaker logged in. Audit Logs page open.', testData:'Action Type: AGGREGATOR_UPDATE', testSteps:'1. Click Filter\n2. Select Action Type: AGGREGATOR_UPDATE\n3. Click Apply Filters\n4. If rows visible: assert badge = AGGREGATOR_UPDATE\n5. If no data: assert "No data found"', expectedResult:'Only AGGREGATOR_UPDATE rows shown, or "No data found".', status:'N/A' },
  { tcId:'TC_AUDITLOG_010', module:'Audit Logs', subModule:'Action Type Filter', testType:'Positive', description:'Filter by Action Type BULK_ONBOARDING returns matching records', preconditions:'AdminMaker logged in. Audit Logs page open.', testData:'Action Type: BULK_ONBOARDING', testSteps:'1. Click Filter\n2. Select Action Type: BULK_ONBOARDING\n3. Click Apply Filters\n4. If rows visible: assert badge = BULK_ONBOARDING\n5. If no data: assert "No data found"', expectedResult:'Only BULK_ONBOARDING rows shown, or "No data found".', status:'N/A' },
  { tcId:'TC_AUDITLOG_011', module:'Audit Logs', subModule:'Action Type Filter', testType:'Positive', description:'Filter by Action Type LOGOUT returns matching records', preconditions:'AdminMaker logged in. Audit Logs page open.', testData:'Action Type: LOGOUT', testSteps:'1. Click Filter\n2. Select Action Type: LOGOUT\n3. Click Apply Filters\n4. Assert first row visible\n5. Assert action badge = LOGOUT', expectedResult:'Rows with Action = LOGOUT visible.', status:'N/A' },
  { tcId:'TC_AUDITLOG_012', module:'Audit Logs', subModule:'Action Type Filter', testType:'Positive', description:'Filter by Action Type FIELD_VALIDATION returns matching records', preconditions:'AdminMaker logged in. Audit Logs page open.', testData:'Action Type: FIELD_VALIDATION', testSteps:'1. Click Filter\n2. Select Action Type: FIELD_VALIDATION\n3. Click Apply Filters\n4. If rows visible: assert badge = FIELD_VALIDATION\n5. If no data: assert "No data found"', expectedResult:'Only FIELD_VALIDATION rows shown, or "No data found".', status:'N/A' },

  // ══════════════════════════════════════════════════════════════════════════
  // REPORTS — TC_RPT_006 (Export)
  // ══════════════════════════════════════════════════════════════════════════
  { tcId:'TC_RPT_006', module:'Reports', subModule:'Export', testType:'Positive', description:'Transaction Summary Report exports successfully as PDF', preconditions:'AdminMaker logged into MMP. Jasper session active.', testData:'Report: Transaction_Summary_Report\nAggregator: AXIAN\nFROM: 1st of month\nTO: Now\nExport format: PDF', testSteps:'1. Open Transaction Summary Report\n2. Set FROM to 1st of month, TO to Now\n3. Select AXIAN aggregator\n4. Click Apply\n5. Assert "Merchant Transaction Summary" visible\n6. Click Export → PDF Document (.pdf)\n7. Assert download event fires\n8. Assert filename ends with .pdf', expectedResult:'Download triggered. Filename ends with .pdf.', status:'N/A' },
];

async function generateFinalMasterReport() {
  const workbook = new ExcelJS.Workbook();
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);

  // ── Sheet 1: All Test Cases ───────────────────────────────────────────────
  const ws = workbook.addWorksheet('All Test Cases');
  ws.columns = [
    { header: 'TC ID',           key: 'tcId',           width: 24 },
    { header: 'Module',          key: 'module',         width: 26 },
    { header: 'Sub-Module',      key: 'subModule',      width: 30 },
    { header: 'Test Type',       key: 'testType',       width: 12 },
    { header: 'Description',     key: 'description',    width: 52 },
    { header: 'Preconditions',   key: 'preconditions',  width: 38 },
    { header: 'Test Data',       key: 'testData',       width: 42 },
    { header: 'Test Steps',      key: 'testSteps',      width: 70 },
    { header: 'Expected Result', key: 'expectedResult', width: 52 },
    { header: 'Status',          key: 'status',         width: 10 },
  ];

  const hdr = ws.getRow(1);
  hdr.height = 32;
  hdr.eachCell(cell => {
    cell.font      = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    cell.fill      = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E3A5F' } };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border    = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
  });

  // Module group header colors
  const moduleColors: Record<string, string> = {
    'Login':                   'FFEBF5FB',
    'Aggregator Management':   'FFEBF8EE',
    'User & Role Management':  'FFFFF3E0',
    'Till Management':         'FFFCE4EC',
    'Notification Management': 'FFF3E5F5',
    'Inbox':                   'FFE8F5E9',
    'Audit Logs':              'FFFFE0B2',
    'Reports':                 'FFEDE7F6',
    'Merchant Onboarding':     'FFE0F7FA',
  };

  testCases.forEach((tc, idx) => {
    const row = ws.addRow(tc);
    row.height = 82;
    const bg = moduleColors[tc.module] ?? (idx % 2 === 0 ? 'FFF4F7FB' : 'FFFFFFFF');

    row.eachCell((cell, col) => {
      cell.alignment = { vertical: 'top', wrapText: true };
      cell.fill      = { type: 'pattern', pattern: 'solid', fgColor: { argb: bg } };
      cell.border    = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };

      if (col === 4) { // Test Type
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        cell.font = tc.testType === 'Positive'
          ? { bold: true, color: { argb: 'FF008A1E' } }
          : { bold: true, color: { argb: 'FFB00020' } };
      }

      if (col === 10) { // Status
        cell.alignment = { vertical: 'middle', horizontal: 'center' };
        if (tc.status === 'PASS') {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF00B050' } };
          cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        } else if (tc.status === 'FAIL') {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFF0000' } };
          cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        } else {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF7A8796' } };
          cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
        }
      }
    });
  });

  // ── Sheet 2: Summary ─────────────────────────────────────────────────────
  const sw = workbook.addWorksheet('Summary');

  const total    = testCases.length;
  const positive = testCases.filter(t => t.testType === 'Positive').length;
  const negative = testCases.filter(t => t.testType === 'Negative').length;
  const pass     = testCases.filter(t => t.status === 'PASS').length;
  const fail     = testCases.filter(t => t.status === 'FAIL').length;
  const na       = testCases.filter(t => t.status === 'N/A').length;

  // Per-module counts
  const modules = [...new Set(testCases.map(t => t.module))];
  const modRows: [string, number][] = modules.map(m => [m, testCases.filter(t => t.module === m).length]);

  const summaryData: (string | number)[][] = [
    ['Project',             'MMP - Merchant Management Portal'],
    ['Report Generated',    new Date().toLocaleString()],
    ['Total Modules',       modules.length],
    ['Total Test Cases',    total],
    ['Positive Cases',      positive],
    ['Negative Cases',      negative],
    ['', ''],
    ['PASS',                pass],
    ['FAIL',                fail],
    ['N/A (not yet run)',   na],
    ['Pass Rate',           `${((pass / total) * 100).toFixed(1)}%`],
    ['', ''],
    ['— By Module —',       ''],
    ...modRows,
  ];

  summaryData.forEach((item, rowIdx) => {
    const row = sw.addRow(item);
    row.getCell(1).font = { bold: true };
    row.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: rowIdx < 12 ? 'FFE8EFF7' : 'FFF5F8FF' } };
    [1, 2].forEach(c => {
      row.getCell(c).border = { top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' } };
    });
    if (item[0] === 'PASS') { row.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF00B050' } }; row.getCell(2).font = { bold: true, color: { argb: 'FFFFFFFF' } }; }
    if (item[0] === 'FAIL') { row.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFF0000' } }; row.getCell(2).font = { bold: true, color: { argb: 'FFFFFFFF' } }; }
  });

  sw.getColumn(1).width = 28;
  sw.getColumn(2).width = 50;

  // ── Save ─────────────────────────────────────────────────────────────────
  const reportsDir = path.join(__dirname, '..', 'reports');
  if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir, { recursive: true });

  const outFile = path.join(reportsDir, `MMP_Automation_Testing_${timestamp}.xlsx`);
  await workbook.xlsx.writeFile(outFile);
  console.log(`Report saved: ${outFile}`);
  console.log(`Total test cases: ${total} | PASS: ${pass} | FAIL: ${fail} | N/A: ${na}`);
}

generateFinalMasterReport().catch(err => { console.error(err); process.exit(1); });
